name: jupyter-tips
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - ipywidgets=8.1.5
  - jupyterlab=4.3.3
  - jupyterlab-spellchecker=0.8.4
  - nbqa
  - nodejs=22.12.0
  - numpy=2.2.0
  - pandas=2.2.3
  - pip=24.3.1
  - python=3.11
  - scikit-learn=1.6.0
